name: Interferencias

baseurl: /

gems:
  - jekyll-paginate

paginate: 4

permalink: pretty

nav:
  - /info
  - /contact
  - /join
  - /links

authors:
  paula:
    name: Paula
    link: "https://github.com/terceranexus6"
  germaaan:
    name: germaaan
    link: "https://github.com/germaaan"

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
