name: Interferencias

baseurl: /

gems:
  - jekyll-paginate

paginate: 4

permalink: pretty

nav:
  - /info
  - /contact
  - /join
  - /links

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
